### ISSUE TITLE
Unable to connect - Login required

### ISSUE THREAD

**Issue by PineVise** [Kismon/kismon#12]
Kismet: 2019-04-GIT
Kismon: 1.0.0

When I try to connect Kismon to a Kismet server running on another machine on the network, it returns the following both in the console and the Log window in the Kismon UI:
`Error: <h1>401 - Access denied</h1>Login required to access this resource.`

In the server configuration in Kismon the address, port, and username/password are correct and match the kismet_httpd.conf settings. I checked that Kismet isn't overriding the user httpd configuration as well. In the browser of the machine, the Kismet UI is accessible with the username/password that is provided to Kismon.

Kismon does connect to the server, it just isn't passing the credentials in a way that Kismet accepts possibly?

**Comment by dreadnought** [comment]
Looks like the problem was introduced by this commit: https://github.com/kismetwireless/kismet/commit/932377f5f96e7b31d8e6473b0e3361cdc6c81ef6

Before that the kismet server needed only authentication for endpoints that configure the server, now it requires it for all requests.

I will update Kismon in the next days to reflect this change, until then you could use the kismet release kismet-2019-04-R1 instead of the git master.
